SDKCF-4559 refactored RDeviceIdentifier API
rakutentech/ios-sdkutils pull request #22
Opened 2021-11-10 15:01 UTC by apparition47

Refactor of #21.

## Notable Changes
* incompatible with Obj-C
* doesn't use RLogger; `throws` instead
* 

## Public APIs
```swift
public enum RDeviceIdentifier {
    public static func getUniqueDeviceIdentifier(service: String, accessGroup: String) throws -> String
    public static var modelIdentifier: String
}
public enum RDeviceIdentifierError: Error {
    case accessControl
    case entitlements(accessGroup: String)
    case keychainLocked
    case queryFailed(status: OSStatus)
    case internalError
}
```

If calling `RDeviceIdentifier.getUniqueDeviceIdentifier(service:accessGroup:)`, an `.entitlements` must be created with an id (used for Keychain Sharing). This should correspond the value passed into the `accessGroup` argument. 

![](https://user-images.githubusercontent.com/40610/67627072-333b1580-f890-11e9-9feb-bf507abc2724.png)

2021-11-16 12:28 UTC, malayli commented on Sources/RDeviceIdentifier/RDeviceIdentifierKeychain.swift
> +    init(service: String, accessGroup: String) {
I think that the init is not needed as it is automatically generated for structs.

2021-11-16 12:31 UTC, malayli commented on Sources/RDeviceIdentifier/RDeviceIdentifier.swift
> +    public static func getUniqueDeviceIdentifier(service: String, accessGroup: String) throws -> String {
`get` prefix sounds like Java. Maybe `uniqueDeviceIdentifier(for service: String, accessGroup: String)` is more swifty.

2021-11-16 12:34 UTC, malayli commented on Sources/RDeviceIdentifier/RDeviceIdentifier.swift
> +        let keychain = RDeviceIdentifierKeychain(service: service, accessGroup: accessGroup)
In this new architecture, is it possible to inject the keychain in an internal function `getUniqueDeviceIdentifier` that would be:
`public static func getUniqueDeviceIdentifier(service: String, accessGroup: String, keychain: RDeviceIdentifierKeychainable) throws -> String`
Where RDeviceIdentifierKeychainable is a protocol that RDeviceIdentifierKeychain implements.
?

So we can use this function to inject a mock of RDeviceIdentifierKeychain in the target tests.

2021-11-17 06:21 UTC, donnie-jp requested changes
@apparition47 Due to SDKCF-4580 it looks like we won't be needing this refactor. Please close or convert to draft and keep the branch aside for now. Thanks

2021-11-17 06:44 UTC, closed without merging