chore: prepare 2.1.0 release (SDKCF-4464)
rakutentech/ios-sdkutils pull request #36
Opened 2022-04-05 12:43 UTC by apparition47

2022-04-06 13:38 UTC, imaginaris requested changes

2022-04-06 13:38 UTC, imaginaris commented on CHANGELOG.md
> +Improve:
Missing `-` at the beginning

2022-04-06 13:38 UTC, imaginaris commented on CHANGELOG.md
> +#### 3.0.0 (2022-04-06)
Can you add also SDKCF-4826. It was about setting up sonarcloud and sonarqube and ensuring that quality gate passes (by adding more unit tests). I'm not sure how to put that nicely in once sentence, I'm bad ad this. Tanomu 🙏

2022-04-07 04:44 UTC, donnie-jp approved these changes

2022-04-07 13:21 UTC, malayli approved these changes

2022-04-08 01:46 UTC, merged